// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/objects/get-event-types-list": {
            "get": {
                "description": "Метод для получения списка типов событий",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Объекты"
                ],
                "summary": "Получение списка типов событий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/objects.GetEventTypesListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/get-object-data/{id}": {
            "get": {
                "description": "Метод для получения данных о конкретном объекте (метки на карте)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Объекты"
                ],
                "summary": "Получение данных для конкретного объекта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемого объекта (метки на карте)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/objects.ObjectInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/get-objects-list": {
            "post": {
                "description": "Метод для получения списка объектов с возможностью фильтрации по типам событий и датам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Объекты"
                ],
                "summary": "Получение списка объектов",
                "parameters": [
                    {
                        "description": "Параметры фильтрации (опционально)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/objects.GetObjectsListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/objects.GetObjectsListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "objects.EventTypeInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "objects.GetEventTypesListResp": {
            "type": "object",
            "properties": {
                "eventTypes": {
                    "description": "EventTypes - массив словарей, каждый элемент которого содержит:\nid - ID типа события\nname - название типа события\ndescription - описание типа события",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/objects.EventTypeInfo"
                    }
                }
            }
        },
        "objects.GetObjectsListReq": {
            "type": "object",
            "properties": {
                "dateFrom": {
                    "type": "string"
                },
                "dateTo": {
                    "type": "string"
                },
                "eventTypeIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "objects.GetObjectsListResp": {
            "type": "object",
            "properties": {
                "objects": {
                    "description": "Objects - массив словарей, каждый элемент которого содержит:\nid - ID объекта\ntitle - название объекта\ndescription - описание объекта\ncoordinates - координаты объекта\neventDate - дата события объекта\neventType - тип объекта\npreviewUrlImage - URL картинки превью объекта",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/objects.ObjectInfo"
                    }
                }
            }
        },
        "objects.ObjectInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "eventType": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "previewUrlImage": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Документация API исторической платформы",
	Description:      "Серверное REST API исторической платформы, разработанное на Go с использованием Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
