// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/objects/get-event-types-list": {
            "get": {
                "description": "Метод для получения списка типов событий.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Метки"
                ],
                "summary": "Получение списка типов событий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "events"
                        }
                    }
                }
            }
        },
        "/objects/get-object-data/{id}": {
            "get": {
                "description": "Метод для получения данных о конкретном объекте (метки на карте)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Объекты"
                ],
                "summary": "Получение данных для конкретного объекта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемого объекта (метки на карте)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/objects.ObjectInfo"
                        }
                    }
                }
            }
        },
        "/objects/get-objects-list": {
            "get": {
                "description": "Метод для получения списка объектов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Объекты"
                ],
                "summary": "Получение списка объектов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "objects"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "objects.ObjectInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "eventType": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "previewUrlImage": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7666",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Документация API исторической платформы",
	Description:      "Серверное REST API исторической платформы, разработанное на Go с использованием Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
